/*
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.validation;

/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class LuaValidator extends AbstractLuaValidator {
}
