/**
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.tests;

import com.google.inject.Injector;
import com.google.inject.Provider;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.stream.Stream;
import javax.inject.Inject;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.resource.XtextResourceSet;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.lua.LuaStandaloneSetup;
import org.xtext.lua.lua.Chunk;

@Disabled
@ExtendWith(InjectionExtension.class)
@InjectWith(LuaInjectorProvider.class)
public class LuaParsingTest {
	@Inject
	@Extension
	private ParseHelper<Chunk> _parseHelper;

	@Inject
	@Extension
	private Provider<XtextResourceSet> _provider;

	@Inject
	@Extension
	private ValidationTestHelper _validationTestHelper;

	private final String luaSnippet =
		"num = 666\n\n"
		+ "local function foo()\n\t"
		+ "num = num + 1\n"
		+ "end\n\n"
		+ "foo()\n"
		+ "eq = num == 667";

	/**
	 * this is critical, as parsing it using the ParseHelper will create a synthetic
	 * resource, where our stdlib injection scheme does _not_ work.
	 */
	private final String luaSnippetWithStdLib =
		"local function foo()\n\t"
		+ "print(\"foo bar\")\n"
		+ "end\n\n"
		+ "foo()";

	@Test
	public void loadModel() throws Exception {
		final Chunk result = this._parseHelper.parse(this.luaSnippet);
  		Assertions.assertNotNull(result);
		final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
		Assertions.assertTrue(errors.isEmpty(), "Unexpected errors: " + IterableExtensions.join(errors, ", "));
	}

	public void assertEqualsCodeAndParsedPrinted(final String orig) throws Exception {
		final Chunk result = this._parseHelper.parse(orig);
  		this._validationTestHelper.assertNoIssues(result);
  		
  		final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
  		result.eResource().save(outputStream, null);
  		final String parsedAndPrinted = outputStream.toString();
  		
  		final String expected = orig;
  		final String actual = parsedAndPrinted;
  		Assertions.assertEquals(expected, actual);
	}

	@Test
	public void testSimpleCode() throws Exception {
		this.assertEqualsCodeAndParsedPrinted(this.luaSnippet);
	}

	@Test
	public void testXMIexport() throws IOException {
//		Setting the path like this did not work surprisingly: 
//		new StandaloneSetup().platformUri = "./test-data/"
		final Injector injector = new LuaStandaloneSetup().createInjectorAndDoEMFRegistration();
		XtextResourceSet rs = injector.<XtextResourceSet>getInstance(XtextResourceSet.class);
		Resource r1 = rs.getResource(URI.createURI("./src/test/resources/foo.lua"), true);
		r1.load(null);
		Resource r2 = rs.createResource(URI.createURI("./target/test-data/foo.xmi"));
		r2.getContents().add(r1.getContents().get(0));
		r2.save(null);
	}

	/**
	 * This brings a string into a form where we can compare it to another of the
	 * same form This prevents false positives from whitespace, comment which would
	 * otherwise create differences between the two strings.
	 */
	public String bringIntoCanonicalForm(final String luaCode) {
		// strip comments
		String striped = luaCode.replaceAll("(?m)--[^\n]*\n?", "");
		
		// to leading and trailingwhite space characters
		striped = striped.replaceAll("(?m)^[\t ]*", "");
		striped = striped.replaceAll("(?m)[\t ]*$", "");
		
		// only one newline between lines
		striped = striped.replaceAll("[\r\n]+", "\n");
		
		// no newlines in first and last line 
		return striped.trim();
	}

	public String bringIntoExtremelyCanonicalForm(final String canonicalForm) {
		// spaces my occur in the original file
		// this breaks strings, but that doesn't matter here
		String canonical = canonicalForm.replaceAll("[\t ]+", "");
		
		// no newlines in first and last line
		return canonical.replaceAll("\n", "");
	}

	public boolean checkCaseStudyFile(final XtextResourceSet rs, final Path srcFile, final Path appPath,
			final String name) throws IOException {
		final URI uri = URI.createURI(srcFile.toString());
	  	final Resource res = rs.getResource(uri, true);
	  	final String origString = Files.readString(srcFile);
	  	
	  	final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
	  	res.save(outputStream, null);
	  	final String parsedAndPrinted = outputStream.toString();
	  	
	  	// strip things like unimportant whitespace, duplicate newlines, etc.
	  	final String origCanonical = this.bringIntoCanonicalForm(origString);
	  	final String parsedAndPrintedCanonical = this.bringIntoCanonicalForm(parsedAndPrinted);
	  	
        // further also strip _all_ newlines and whitespace
	 	// this definitely breaks the file, but that does not matter for the string comparision
	  	final String origExtremelyCanonical = this.bringIntoExtremelyCanonicalForm(origCanonical);
	  	final String parsedAndPrintedExtremelyCanonical = this.bringIntoExtremelyCanonicalForm(parsedAndPrintedCanonical);
	  	
	  	this._validationTestHelper.assertNoIssues(res);
	  	final boolean equivalence = origExtremelyCanonical.equals(parsedAndPrintedExtremelyCanonical);
	  	
	    // write strings to files if there are differences
	  	if ((!equivalence)) {
		    final Path targetDir = Paths.get("./caseStudyEvaluation/").resolve(name).resolve(appPath.relativize(srcFile));
			final Path plainDir = targetDir.resolve("plain");
			final Path canonicalDir = targetDir.resolve("canonical");
			final Path extremelyCanonicalDir = targetDir.resolve("extremely-canonical");
			Files.createDirectories(plainDir);
			Files.createDirectories(canonicalDir);
			Files.createDirectories(extremelyCanonicalDir);
			Files.writeString(plainDir.resolve("orig.lua"), origString);
			Files.writeString(plainDir.resolve("parsedAndPrinted.lua"), parsedAndPrinted);
			Files.writeString(canonicalDir.resolve("orig.lua"), origCanonical);
			Files.writeString(canonicalDir.resolve("parsedAndPrinted.lua"), parsedAndPrintedCanonical);
			Files.writeString(extremelyCanonicalDir.resolve("orig.lua"), origExtremelyCanonical);
			Files.writeString(extremelyCanonicalDir.resolve("parsedAndPrinted.lua"), parsedAndPrintedExtremelyCanonical);
	  	}
	    return equivalence;
	}

	public void checkApp(final Path appPath, final String name) throws IOException {
		final XtextResourceSet rs = this._provider.get();
		final PathMatcher matcher = FileSystems.getDefault().getPathMatcher("glob:**.lua");
		
		final ArrayList<Path> equalPaths = new ArrayList<Path>();
		final ArrayList<Path> unequalPaths = new ArrayList<Path>();
		
		try (final Stream<Path> paths =  Files.walk(appPath)) {
			paths.filter(matcher::matches).forEach((Path path) -> {
				final Path relPath = appPath.relativize(path);
				try {
					if (this.checkCaseStudyFile(rs, path, appPath, name)) {
						equalPaths.add(relPath);
					} else {
						unequalPaths.add(relPath);
					}
				} catch (IOException e) {
					throw new IllegalStateException(e);
				}
			});
		}
		
		System.out.printf("Equivalent files: %d %s\n", equalPaths.size(), equalPaths);
		System.out.printf("Not equivalent files: %d %s\n", unequalPaths.size(), unequalPaths);
		Assertions.assertTrue(unequalPaths.isEmpty(), "Files which failed check: " + unequalPaths.toString());
	}

	@Disabled("Code not yet available.")
	@Test
	public void testCaseStudy1CodeModelCorrectness() throws IOException {
		final Path appPath = Paths.get("../caseStudy1");
		this.checkApp(appPath, "CaseStudy1");
	}
}
