/**
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.tests;

import javax.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.testing.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Extension;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.lua.lua.Chunk;
import org.xtext.lua.lua.Expression_Functioncall_Direct;
import org.xtext.lua.lua.Expression_TableConstructor;
import org.xtext.lua.lua.Expression_VariableName;
import org.xtext.lua.lua.Field_AddEntryToTable;
import org.xtext.lua.lua.Refble;
import org.xtext.lua.lua.Referenceable;
import org.xtext.lua.lua.Statement_Global_Assignment;
import org.xtext.lua.lua.Statement_Local_Assignment;

/**
 * check if a references point to the correct refbles
 */
@ExtendWith(InjectionExtension.class)
@InjectWith(LuaInjectorProvider.class)
public class LuaScopingTest {
	@Inject
	@Extension
	private ParseHelper<Chunk> _parseHelper;

	@Inject
	@Extension
	private ValidationTestHelper _validationTestHelper;

	public Chunk getParsedChunk(final String snippet) throws Exception {
		final Chunk chunk = this._parseHelper.parse(snippet);
		Assertions.assertTrue(chunk.eResource().getErrors().isEmpty());
		this._validationTestHelper.assertNoIssues(chunk);
		return chunk;
	}

	@Test
	public void testRefFunctionDecl() throws Exception {
		final String snippet = """
			function foo(...)
			end
			result = foo()
			foo()
		""";
		final Chunk parsed = this.getParsedChunk(snippet);
		Assertions.assertEquals(3, parsed.getBlock().getStatements().size());
		
		final Refble foo = (Refble) parsed.getBlock().getStatements().get(0);
		
		// with assignment
		final Statement_Global_Assignment hasCall = (Statement_Global_Assignment) parsed.getBlock().getStatements().get(1);
		final Expression_Functioncall_Direct fooCall = (Expression_Functioncall_Direct) hasCall.getValues().get(0);
		final Refble fooRef = fooCall.getCalledFunction();
		Assertions.assertEquals(foo, fooRef);
		
		// without assignment
		final Expression_Functioncall_Direct fooCallFlat = (Expression_Functioncall_Direct) parsed.getBlock().getStatements().get(2);
		final Refble fooRefFlat = fooCallFlat.getCalledFunction();
		Assertions.assertEquals(foo, fooRefFlat);
	}

	@Test
	public void testRefFunctionDeclLocal() throws Exception {
		final String snippet = """
			local function foo(...)
			end
			local result = foo()
			foo()
		""";
		final Chunk parsed = this.getParsedChunk(snippet);
		Assertions.assertEquals(3, parsed.getBlock().getStatements().size());
		
		final Refble foo = (Refble) parsed.getBlock().getStatements().get(0);
		
		// with assignment
		final Statement_Local_Assignment hasCall = (Statement_Local_Assignment) parsed.getBlock().getStatements().get(1);
		final Expression_Functioncall_Direct fooCall = (Expression_Functioncall_Direct) hasCall.getValues().get(0);
		final Refble fooRef = fooCall.getCalledFunction();
		Assertions.assertEquals(foo, fooRef);
		
		// without assignment
		final Expression_Functioncall_Direct fooCallFlat = (Expression_Functioncall_Direct) parsed.getBlock().getStatements().get(2);
		final Refble fooRefFlat = fooCallFlat.getCalledFunction();
		Assertions.assertEquals(foo, fooRefFlat);
	}

	@Test
	public void testRefSimpleAssignment() throws Exception {
		final String snippet = """
			bar = 42
			result = bar
		""";
		final Chunk parsed = this.getParsedChunk(snippet);
		Assertions.assertEquals(2, parsed.getBlock().getStatements().size());
		
		final Statement_Global_Assignment hasBar = (Statement_Global_Assignment) parsed.getBlock().getStatements().get(0);
		final Referenceable bar = (Referenceable) hasBar.getDests().get(0);
		
		final Statement_Global_Assignment hasRef = (Statement_Global_Assignment) parsed.getBlock().getStatements().get(1);
		final Refble barRef = ((Expression_VariableName) hasRef.getValues().get(0)).getRef();
		
		// check if barRef points to bar
		Assertions.assertEquals(bar, barRef);
	}

	/**
	 * check if a reference points to the correct refble 
	 */
	@Test
	public void testRefTableAssignment() throws Exception {
		final String snippet = """
			Foo = {
					bar = 42
				}
				result = Foo.bar
		""";
		final Chunk parsed = this.getParsedChunk(snippet);
		Assertions.assertEquals(2, parsed.getBlock().getStatements().size());
		
		final Statement_Global_Assignment hasBar = (Statement_Global_Assignment) parsed.getBlock().getStatements().get(0);
		final Expression_TableConstructor fooList = (Expression_TableConstructor) hasBar.getValues().get(0);
		// this field is refble
		final Field_AddEntryToTable bar = (Field_AddEntryToTable) fooList.getFields().get(0);
		
		final Statement_Global_Assignment hasRef = (Statement_Global_Assignment) parsed.getBlock().getStatements().get(1);
		final Refble barRef = ((Expression_VariableName) hasRef.getValues().get(0)).getRef();
		
		// check if barRef points to bar
		Assertions.assertEquals(bar, barRef);
	}
}
