/**
 * generated by Xtext 2.28.0
 */
package org.xtext.lua.tests;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Set;
import java.util.function.Consumer;
import javax.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.lua.lua.Chunk;

@ExtendWith(InjectionExtension.class)
@InjectWith(LuaInjectorProvider.class)
@SuppressWarnings("all")
public class LuaScopingFailuresTest {
	@Inject
	@Extension
	private ParseHelper<Chunk> _parseHelper;

	private final Set<String> failureSrc = Set.of(
		// no self reference
		"""
			hello = hello
		""",
		// no access to uncalled function
		"""
			local function foo(...)
				local bar = 42
			end
			
			result = bar
		""",
		// Cannot declare a qualified function without declaring the table first
		"""
			function Foo.bar(...)
			end
		"""
	);

	@Disabled("We assume a correct grammar for the evaluation, because finding all errors is very hard")
	@Test
	public void testFailureScoping() {
		final ArrayList<String> falsePositives = new ArrayList<>();
		this.failureSrc.forEach((String it) -> {
			try {
				final Chunk result = this._parseHelper.parse(it);
				final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
//				ValidationTestHelper.assertIssue(result, Chunk.eClass, "Foo", Severity.INFO)
//				assertIssue(result, result.eClass,)
				if (errors.isEmpty()) {
					falsePositives.add("Missing expected errors in: " + it);
				}
			} catch (Exception e) {
				throw new IllegalStateException(e);
			}
		});
		Assertions.assertTrue(falsePositives.isEmpty(), "There were false positives: " + IterableExtensions.join(falsePositives, "\n"));
	}
}
