<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <artifactId>tools.cipm.models.instrumentation</artifactId>
	<version>1.0.1</version>
    <packaging>jar</packaging>
    <name>Instrumentation Metamodel</name>

    <parent>
        <groupId>tools.cipm</groupId>
        <artifactId>metamodels.parent</artifactId>
        <version>1.0.1</version>
    </parent>
    
    <repositories>
        <repository>
            <id>cipm-mvn</id>
            <name>CIPM's Maven Repository</name>
            <url>https://CIPM-tools.github.io/updatesite/mvn</url>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>${project.basedir}</directory>
                <includes>
                    <include>plugin.properties</include>
                    <include>plugin.xml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
			<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>mwe2Launcher</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <mainClass>org.eclipse.emf.mwe2.launch.runtime.Mwe2Launcher</mainClass>
                            <arguments>
                                <argument>/${project.basedir}/src/gen/generate.mwe2</argument>
                            </arguments>
                            <classpathScope>compile</classpathScope>
                            <includePluginDependencies>true</includePluginDependencies>
                            <cleanupDaemonThreads>false</cleanupDaemonThreads><!-- see https://bugs.eclipse.org/bugs/show_bug.cgi?id=475098#c3 -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>bundle</goal>
                        </goals>
                        <configuration>
							<instructions>
								<Export-Package>tools.cipm.models.*</Export-Package>
								<Bundle-SymbolicName>${project.artifactId};singleton:=true</Bundle-SymbolicName>
							</instructions>
						</configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/generated</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-clean</id>
                        <configuration>
                            <filesets>
                                <fileset>
                                    <directory>${project.basedir}/src/main/generated</directory>
                                </fileset>
                            </filesets>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.codehaus.mojo</groupId>
                                        <artifactId>exec-maven-plugin</artifactId>
                                        <versionRange>[1.6.0,)</versionRange>
                                        <goals>
                                            <goal>java</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-clean-plugin</artifactId>
                                        <versionRange>[3.1.0,)</versionRange>
                                        <goals>
                                            <goal>clean</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore></ignore>
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.common</artifactId>
			<version>2.20.0</version>
        </dependency>
		<dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
			<version>2.20.0</version>
        </dependency>
        <dependency>
        	<groupId>org.eclipse.xtext</groupId>
        	<artifactId>org.eclipse.xtext.xtext.generator</artifactId>
            <version>2.28.0</version>
            <scope>provided</scope>
        </dependency>
		<dependency>
        	<groupId>org.eclipse.xtext</groupId>
        	<artifactId>org.eclipse.xtext.common.types</artifactId>
            <version>2.28.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
        	<groupId>org.eclipse.emf</groupId>
        	<artifactId>org.eclipse.emf.mwe2.launch</artifactId>
            <version>2.13.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.core</groupId>
            <artifactId>org.palladiosimulator.pcm</artifactId>
            <version>5.0.0.202102051710</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.identifier</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.probfunction</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.units</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.stoex</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2</groupId>
            <artifactId>org.eclipse.uml2.codegen.ecore</artifactId>
            <version>2.5.2.v20210228-1829</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo</artifactId>
            <version>4.19.0.v20220907-1437</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo.common</artifactId>
            <version>4.19.0.v20220907-1437</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.net4j</groupId>
            <artifactId>org.eclipse.net4j.util</artifactId>
            <version>3.20.0.v20220907-1437</version>
        </dependency>
    </dependencies>
</project>
